### ISSUE TITLE
Práctica 5

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-ycej#2]
[Práctica 5_Edwin_Yanet_Carlos_Jeronima.pdf](https://github.com/user-attachments/files/17164590/Practica.5_Edwin_Yanet_Carlos_Jeronima.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by Julissamigdalia** [comment]
Calificación :20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
